<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM1wmuj9\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM1wmuj9/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerM1wmuj9.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerM1wmuj9\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerM1wmuj9\appDevDebugProjectContainer([
    'container.build_hash' => 'M1wmuj9',
    'container.build_id' => 'ddb4745f',
    'container.build_time' => 1606102137,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM1wmuj9');
