<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2orvrae\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2orvrae/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2orvrae.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2orvrae\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2orvrae\appDevDebugProjectContainer([
    'container.build_hash' => '2orvrae',
    'container.build_id' => 'd79a99ba',
    'container.build_time' => 1606218773,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2orvrae');
