<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'activity_live_replay_event_subscriber' shared service.

return $this->services['activity_live_replay_event_subscriber'] = new \Biz\Activity\Event\LiveReplayEventSubscriber(${($_ = isset($this->services['biz']) ? $this->services['biz'] : $this->getBizService()) && false ?: '_'});
