<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_authentication_manager' shared service.

return $this->services['api_authentication_manager'] = new \ApiBundle\Security\Authentication\ResourceAuthenticationProviderManager($this, [0 => ${($_ = isset($this->services['api_default_authentication']) ? $this->services['api_default_authentication'] : ($this->services['api_default_authentication'] = new \ApiBundle\Security\Authentication\DefaultResourceAuthenticationProvider($this))) && false ?: '_'}]);
