<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_session_authentication_listener' shared service.

return $this->services['api_session_authentication_listener'] = new \ApiBundle\Security\Firewall\SessionAuthenticationListener($this);
