<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api.util.item_helper' shared service.

return $this->services['api.util.item_helper'] = new \ApiBundle\Api\Util\ItemHelper(${($_ = isset($this->services['biz']) ? $this->services['biz'] : $this->getBizService()) && false ?: '_'}, $this);
