<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_response_viewer' shared service.

return $this->services['api_response_viewer'] = new \ApiBundle\Viewer($this);
