<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'custom.activity.extension' shared service.

$this->services['custom.activity.extension'] = $instance = new \CustomBundle\Extension\ActivityExtension();

$instance->setBiz(${($_ = isset($this->services['biz']) ? $this->services['biz'] : $this->getBizService()) && false ?: '_'});

return $instance;
