<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'export_factory' shared service.

return $this->services['export_factory'] = new \AppBundle\Component\Export\Factory($this);
