<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'kernel.listener.exception_listener' shared service.

return $this->services['kernel.listener.exception_listener'] = new \AppBundle\Listener\ExceptionListener($this);
