<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oauth2.storage.public_key' shared service.

return $this->services['oauth2.storage.public_key'] = new \OAuth2\Storage\Memory();
