<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oauth2.grant_type.client_credentials' shared service.

return $this->services['oauth2.grant_type.client_credentials'] = new \OAuth2\GrantType\ClientCredentials(${($_ = isset($this->services['oauth2.storage.client_credentials']) ? $this->services['oauth2.storage.client_credentials'] : $this->load('getOauth2_Storage_ClientCredentialsService.php')) && false ?: '_'});
