<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oauth2.grant_type.authorization_code' shared service.

return $this->services['oauth2.grant_type.authorization_code'] = new \OAuth2\GrantType\AuthorizationCode(${($_ = isset($this->services['oauth2.storage.authorization_code']) ? $this->services['oauth2.storage.authorization_code'] : $this->load('getOauth2_Storage_AuthorizationCodeService.php')) && false ?: '_'});
