<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access_map' shared service.

$this->services['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/crontab'), [0 => 'IS_AUTHENTICATED_ANONYMOUSLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/task'), [0 => 'ROLE_USER'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/my'), [0 => 'ROLE_USER'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/settings'), [0 => 'ROLE_USER'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/cashier'), [0 => 'ROLE_USER'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/order'), [0 => 'ROLE_USER'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/message'), [0 => 'ROLE_USER'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/classroom/\\d+/manage/'), [0 => 'ROLE_USER'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/admin/course'), [0 => 'ROLE_BACKEND'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/admin/user'), [0 => 'ROLE_BACKEND'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/admin/app'), [0 => 'ROLE_BACKEND'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/admin/setting'), [0 => 'ROLE_BACKEND'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/admin/logs'), [0 => 'ROLE_BACKEND'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/admin/upgrade'), [0 => 'ROLE_BACKEND'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/admin/optimize'), [0 => 'ROLE_BACKEND'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/admin'), [0 => 'ROLE_BACKEND'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('/.*'), [0 => 'IS_AUTHENTICATED_ANONYMOUSLY'], NULL);

return $instance;
