<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'topxia.timemachine' shared service.

return $this->services['topxia.timemachine'] = new \AppBundle\Common\TimeMachine('Asia/Shanghai');
