<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'tag_course_set_event_subscriber' shared service.

return $this->services['tag_course_set_event_subscriber'] = new \Biz\Taxonomy\Event\CourseSetEventSubscriber(${($_ = isset($this->services['biz']) ? $this->services['biz'] : $this->getBizService()) && false ?: '_'});
