<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'web.wrapper' shared service.

return $this->services['web.wrapper'] = new \AppBundle\Component\Wrapper\WrapperManage($this);
