<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'assets.static_version_strategy' shared service.

return $this->services['assets.static_version_strategy'] = new \AppBundle\Twig\Asset\VersionStrategy\StaticVersionStrategy('', '', ${($_ = isset($this->services['biz']) ? $this->services['biz'] : $this->getBizService()) && false ?: '_'});
