<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_biz_ratelimit_listener' shared service.

return $this->services['api_biz_ratelimit_listener'] = new \ApiBundle\EventListener\BizRateLimitListener(${($_ = isset($this->services['biz']) ? $this->services['biz'] : $this->getBizService()) && false ?: '_'});
