<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'course_product_event_subscriber' shared service.

return $this->services['course_product_event_subscriber'] = new \Biz\S2B2C\Event\CourseProductSubscriber(${($_ = isset($this->services['biz']) ? $this->services['biz'] : $this->getBizService()) && false ?: '_'});
