<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oauth2.storage.scope' shared service.

return $this->services['oauth2.storage.scope'] = new \OAuth2\ServerBundle\Storage\Scope(${($_ = isset($this->services['doctrine.orm.entity_manager']) ? $this->services['doctrine.orm.entity_manager'] : $this->load('getDoctrine_Orm_EntityManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['oauth2.scope_manager']) ? $this->services['oauth2.scope_manager'] : $this->load('getOauth2_ScopeManagerService.php')) && false ?: '_'});
