<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oauth2.grant_type.refresh_token' shared service.

return $this->services['oauth2.grant_type.refresh_token'] = new \OAuth2\GrantType\RefreshToken(${($_ = isset($this->services['oauth2.storage.refresh_token']) ? $this->services['oauth2.storage.refresh_token'] : $this->load('getOauth2_Storage_RefreshTokenService.php')) && false ?: '_'}, ['always_issue_new_refresh_token' => false]);
