<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'qrcode_whitelist_filter' shared service.

return $this->services['qrcode_whitelist_filter'] = new \AppBundle\Component\QrCode\QrCodeWhiteListFilter($this);
