<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'tokenbucket_event_subscriber' shared service.

return $this->services['tokenbucket_event_subscriber'] = new \Biz\PostFilter\Event\TokenBucketEventSubscriber(${($_ = isset($this->services['biz']) ? $this->services['biz'] : $this->getBizService()) && false ?: '_'});
