<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_h5_third_party_oauth2_authentication_listener' shared service.

return $this->services['api_h5_third_party_oauth2_authentication_listener'] = new \ApiBundle\Security\Firewall\H5ThirdPartyOAuth2AuthenticationListener($this);
