<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.entity_manager.driver.yaml' shared service.

return $this->services['doctrine.entity_manager.driver.yaml'] = new \Doctrine\ORM\Mapping\Driver\SimplifiedYamlDriver($this->getParameter('doctrine.config_paths'));
