<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'permission.admin_voter' shared service.

return $this->services['permission.admin_voter'] = new \AppBundle\SfExtend\AdminVoter();
