imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

twig:
    globals:
        site_tracking: false
swiftmailer:
    disable_delivery:  false

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: warning
            formatter: json_formatter
        firephp:
            type:  firephp
            level: info

services:
    app.cloud_api_collector:
        class: AppBundle\DataCollector\CloudApiDataCollector
        arguments: ['@Biz']
        tags:
            - { name: data_collector, template: 'webprofiler/cloud-api.html.twig', id: 'app.cloud_api_collector'}