<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_web_lib_listener' shared service.

return $this->services['api_web_lib_listener'] = new \ApiBundle\Security\Firewall\WebLibAuthenticationListener($this);
