<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'activity_runtime_container' shared service.

return $this->services['activity_runtime_container'] = new \AppBundle\Component\Activity\ActivityRuntimeContainer($this);
