<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api.path.parser' shared service.

return $this->services['api.path.parser'] = new \ApiBundle\Api\PathParser();
