<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api.plugin.config.manager' shared service.

return $this->services['api.plugin.config.manager'] = new \Codeages\PluginBundle\System\PluginConfigurationManager($this->targetDirs[2]);
