<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'bazinga.jstranslation.dump_command' shared service.

$this->services['bazinga.jstranslation.dump_command'] = $instance = new \Bazinga\Bundle\JsTranslationBundle\Command\DumpCommand(${($_ = isset($this->services['bazinga.jstranslation.translation_dumper']) ? $this->services['bazinga.jstranslation.translation_dumper'] : $this->load('getBazinga_Jstranslation_TranslationDumperService.php')) && false ?: '_'}, $this->targetDirs[2]);

$instance->setName('bazinga:js-translation:dump');

return $instance;
