<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'codeags_plugin.event.lazy_subscribers' shared service.

$this->services['codeags_plugin.event.lazy_subscribers'] = $instance = new \Codeages\PluginBundle\Event\LazySubscribers($this);

$instance->addSubscriberService('article_article_event_subscriber');
$instance->addSubscriberService('activity_live_replay_event_subscriber');
$instance->addSubscriberService('course_classroom_course_expiry_date_event_subscriber');
$instance->addSubscriberService('order_subscriber');
$instance->addSubscriberService('app_order_subscriber');
$instance->addSubscriberService('card_event_subscriber');
$instance->addSubscriberService('course_note_event_subscriber');
$instance->addSubscriberService('course_member_event_subscriber');
$instance->addSubscriberService('content_event_subscriber');
$instance->addSubscriberService('user_course_thread_event_subscriber');
$instance->addSubscriberService('user_classroom_event_subscriber');
$instance->addSubscriberService('user_user_event_subscriber');
$instance->addSubscriberService('user_vip_member_event_subscriber');
$instance->addSubscriberService('task_event_subscriber');
$instance->addSubscriberService('taxonomy_article_event_subscriber');
$instance->addSubscriberService('activity_event_subscriber');
$instance->addSubscriberService('video_task_event_subscriber');
$instance->addSubscriberService('course_statistics_event_subscriber');
$instance->addSubscriberService('course_thread_subscriber');
$instance->addSubscriberService('course_set_statistics_event_subscriber');
$instance->addSubscriberService('course_set_teacher_event_subscriber');
$instance->addSubscriberService('course_set_event_subscriber');
$instance->addSubscriberService('upload_file_event_subscriber');
$instance->addSubscriberService('course_sync_event_subscriber');
$instance->addSubscriberService('task_sync_event_subscriber');
$instance->addSubscriberService('course_set_material_event_subscriber');
$instance->addSubscriberService('conversation_event_subscriber');
$instance->addSubscriberService('notification_event_subscriber');
$instance->addSubscriberService('opencourse_event_subscriber');
$instance->addSubscriberService('orderrefererlog_event_subscriber');
$instance->addSubscriberService('tokenbucket_event_subscriber');
$instance->addSubscriberService('sms_task_event_subscriber');
$instance->addSubscriberService('sms_testpaper_event_subscriber');
$instance->addSubscriberService('sms_pay_center_event_subscriber');
$instance->addSubscriberService('thread_event_subscriber');
$instance->addSubscriberService('classroom_event_subscriber');
$instance->addSubscriberService('course_material_event_subscriber');
$instance->addSubscriberService('tag_course_set_event_subscriber');
$instance->addSubscriberService('testpaper_event_subscriber');
$instance->addSubscriberService('status_event_subscriber');
$instance->addSubscriberService('classroom_member_event_subscriber');
$instance->addSubscriberService('course_try_view_subscriber');
$instance->addSubscriberService('crontab_event_subscriber');
$instance->addSubscriberService('learning_progress_event_subscriber');
$instance->addSubscriberService('open_course_sms_event_subscriber');
$instance->addSubscriberService('statement_event_subscriber');
$instance->addSubscriberService('user_account_event_subscriber');
$instance->addSubscriberService('task_testpaper_event_subscriber');
$instance->addSubscriberService('wechat_notification_event_subscriber');
$instance->addSubscriberService('coupon_event_subscriber');
$instance->addSubscriberService('navigation_event_subscriber');
$instance->addSubscriberService('destroy_account_event_subscriber');
$instance->addSubscriberService('live_statistics_event_subscriber');
$instance->addSubscriberService('course_product_event_subscriber');

return $instance;
