<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'coupon_service_provider' shared service.

$this->services['coupon_service_provider'] = $instance = new \Biz\Coupon\CouponServiceProvider();

$instance->setBiz(${($_ = isset($this->services['biz']) ? $this->services['biz'] : $this->getBizService()) && false ?: '_'});

return $instance;
