<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.entity_manager.config' shared service.

$this->services['doctrine.entity_manager.config'] = $instance = \Doctrine\ORM\Tools\Setup::createConfiguration(true);

$instance->setMetadataDriverImpl(${($_ = isset($this->services['doctrine.entity_manager.driver.yaml']) ? $this->services['doctrine.entity_manager.driver.yaml'] : $this->load('getDoctrine_EntityManager_Driver_YamlService.php')) && false ?: '_'});
$instance->setEntityNamespaces(['OAuth2ServerBundle' => 'OAuth2\\ServerBundle\\Entity']);

return $instance;
