<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.orm.entity_manager' shared service.

return $this->services['doctrine.orm.entity_manager'] = \Doctrine\ORM\EntityManager::create(['driver' => 'pdo_mysql', 'user' => 'bootcamp', 'password' => 'bootcamp', 'dbname' => 'php-edusoho-exercise', 'host' => '127.0.0.1', 'port' => 3306], ${($_ = isset($this->services['doctrine.entity_manager.config']) ? $this->services['doctrine.entity_manager.config'] : $this->load('getDoctrine_EntityManager_ConfigService.php')) && false ?: '_'});
