<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'endroid.qrcode.factory' shared service.

return $this->services['endroid.qrcode.factory'] = new \Endroid\QrCode\Factory\QrCodeFactory(['size' => 200]);
