<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oauth2.response' shared service.

return $this->services['oauth2.response'] = new \OAuth2\HttpFoundationBridge\Response();
