<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oauth2.grant_type.user_credentials' shared service.

return $this->services['oauth2.grant_type.user_credentials'] = new \OAuth2\GrantType\UserCredentials(${($_ = isset($this->services['oauth2.storage.user_credentials']) ? $this->services['oauth2.storage.user_credentials'] : ($this->services['oauth2.storage.user_credentials'] = new \AppBundle\Component\OAuthServer\Storage\UserCredentials($this))) && false ?: '_'});
