<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sms_pay_center_event_subscriber' shared service.

return $this->services['sms_pay_center_event_subscriber'] = new \Biz\Sms\Event\PayCenterEventSubscriber(${($_ = isset($this->services['biz']) ? $this->services['biz'] : $this->getBizService()) && false ?: '_'});
