<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'topxia.user_provider' shared service.

return $this->services['topxia.user_provider'] = new \Biz\User\UserProvider($this);
