<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'wechat_notification_event_subscriber' shared service.

return $this->services['wechat_notification_event_subscriber'] = new \Biz\WeChatNotification\Event\WeChatNotificationEventSubscriber(${($_ = isset($this->services['biz']) ? $this->services['biz'] : $this->getBizService()) && false ?: '_'});
