<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIbnzeux\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIbnzeux/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIbnzeux.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIbnzeux\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIbnzeux\appDevDebugProjectContainer([
    'container.build_hash' => 'Ibnzeux',
    'container.build_id' => 'ac9ec0b7',
    'container.build_time' => 1606224901,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIbnzeux');
