<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU0usjvn\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU0usjvn/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerU0usjvn.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerU0usjvn\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerU0usjvn\appDevDebugProjectContainer([
    'container.build_hash' => 'U0usjvn',
    'container.build_id' => 'f6797b61',
    'container.build_time' => 1606218800,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU0usjvn');
