<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'activity_config_manager' shared service.

return $this->services['activity_config_manager'] = new \AppBundle\Component\Activity\ActivityConfigManager($this->targetDirs[0], ($this->targetDirs[2].'/../web/activities'), true);
