<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_default_authentication' shared service.

return $this->services['api_default_authentication'] = new \ApiBundle\Security\Authentication\DefaultResourceAuthenticationProvider($this);
