<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oauth2.storage.user_credentials' shared service.

return $this->services['oauth2.storage.user_credentials'] = new \AppBundle\Component\OAuthServer\Storage\UserCredentials($this);
