<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'templating.loader' shared service.

return $this->services['templating.loader'] = new \Symfony\Bundle\FrameworkBundle\Templating\Loader\FilesystemLoader(${($_ = isset($this->services['codeages_plugin.theme.templating.locator']) ? $this->services['codeages_plugin.theme.templating.locator'] : $this->getCodeagesPlugin_Theme_Templating_LocatorService()) && false ?: '_'});
