imports:
    - { resource: event_subscribers.yml }
    - { resource: oauth2.yml }

services:

    activity_runtime_container:
        class: AppBundle\Component\Activity\ActivityRuntimeContainer
        arguments: ['@service_container']
        public: true

    activity_config_manager:
        class: AppBundle\Component\Activity\ActivityConfigManager
        arguments: ['%kernel.cache_dir%', '%edusoho.activities_dir%', '%kernel.debug%']
        public: true

    user.online_track:
        class: AppBundle\Component\Track\UserOnlineTrack
        arguments: ['@service_container', '@biz']
        public: true

    extension.manager:
        class: AppBundle\Extension\ExtensionManager
        public: true

    activity.extension:
        class: AppBundle\Extension\ActivityExtension
        public: true
        calls:
            - [setBiz, ['@biz']]
        tags:
            - { name: extension, priority: 10 }

    course.extension:
        class: AppBundle\Extension\CourseExtension
        public: true
        calls:
            - [setBiz, ['@biz']]
        tags:
            - { name: extension, priority: 10  }

    copy.extension:
        class: AppBundle\Extension\CopyExtension
        public: true
        calls:
            - [setBiz, ['@biz']]
        tags:
            - { name: extension, priority: 10  }

    task_toolbar.extension:
        class: AppBundle\Extension\TaskToolbarExtension
        public: true
        calls:
            - [setBiz, ['@biz']]
        tags:
            - { name: extension, priority: 10  }

    question.extension:
        class: AppBundle\Extension\QuestionExtension
        public: true
        calls:
            - [setBiz, ['@biz']]
        tags:
            - { name: extension, priority: 10  }

    newcomer_task.extension:
        class: AppBundle\Extension\NewcomerExtension
        public: true
        calls:
            - [setBiz, ['@biz']]
        tags:
            - { name: extension, priority: 10  }

    payment.extension:
        class: AppBundle\Extension\PaymentExtension
        public: true
        calls:
            - [setBiz, ['@biz']]
        tags:
            - { name: extension, priority: 10  }

    callback.extension:
        class: AppBundle\Extension\CallbackExtension
        public: true
        calls:
            - [setBiz, ['@biz']]
        tags:
            - { name: extension }

    wechat_template.extension:
        class: AppBundle\Extension\WeChatTemplateExtension
        public: true
        calls:
            - [setBiz, ['@biz']]
        tags:
            - { name: extension, priority: 10 }

    biz.service_provider.collector:
        class: Biz\ServiceProviderCollector
        public: true

    coupon_service_provider:
        class: Biz\Coupon\CouponServiceProvider
        public: true
        calls:
            - [setBiz, ['@biz']]
        tags:
            - { name: extension }

    mail_service_provider:
        class: Biz\Mail\MailServiceProvider
        public: true
        calls:
            - [setBiz, ['@biz']]
        tags:
            - { name: extension }

    web.twig.question_type_extension:
        class: AppBundle\Twig\QuestionTypeExtension
        arguments:    ['@service_container', '@biz']
        public: true
        tags:
            - { name: twig.extension }

    web.twig.question_extension:
      class: AppBundle\Twig\QuestionExtension
      arguments:    ['@service_container', '@biz']
      public: true
      tags:
            - { name: twig.extension }

    web.twig.testpaper_extension:
        class: AppBundle\Twig\TestpaperExtension
        arguments:    ['@service_container', '@biz']
        public: true
        tags:
            - { name: twig.extension }

    web.twig.material_extension:
        class: AppBundle\Twig\MaterialExtension
        arguments:    ['@service_container', '@biz']
        public: true
        tags:
            - { name: twig.extension }

    web.twig.app_extension:
        class: AppBundle\Twig\AppExtension
        arguments: ['@service_container']
        public: true
        tags:
            - { name: twig.extension }

    web.twig.activity_extension:
        class: AppBundle\Twig\ActivityExtension
        arguments:    ['@service_container', '@biz']
        public: true
        tags:
            - { name: twig.extension }

    web.twig.live_extension:
        class: AppBundle\Twig\LiveExtension
        arguments:    ['@service_container', '@biz']
        public: true
        tags:
            - { name: twig.extension }

    web.twig.extension:
        class: AppBundle\Twig\WebExtension
        arguments:    ['@service_container', '@biz', '@request_stack']
        public: true
        tags:
            - { name: twig.extension }

    web.twig.html_extension:
        class: AppBundle\Twig\HtmlExtension
        arguments:    ['@service_container', '@biz']
        public: true
        tags:
            - { name: twig.extension }

    web.twig.dictionary_extension:
        class: AppBundle\Twig\DictionaryExtension
        arguments:    ['@service_container', '@biz']
        public: true
        tags:
            - { name: twig.extension }

    web.twig.face_inspection_extension:
        class: AppBundle\Twig\FaceInspectionExtension
        arguments:    ['@service_container', '@biz']
        public: true
        tags:
          - { name: twig.extension }

    web.twig.data_extension:
        class: AppBundle\Twig\DataExtension
        arguments:    ['@service_container', '@biz']
        public: true
        tags:
            - { name: twig.extension }

    web.twig.block_extension:
        class: AppBundle\Twig\BlockExtension
        arguments:    ['@service_container', '@biz']
        public: true
        tags:
            - { name: twig.extension }

    web.twig.uploader_extension:
        class: AppBundle\Twig\UploaderExtension
        arguments:    ['@service_container']
        public: true
        tags:
            - { name: twig.extension }

    web.twig.theme_extension:
        class: AppBundle\Twig\ThemeExtension
        arguments:    ['@service_container', '@biz']
        public: true
        tags:
            - { name: twig.extension }

    web.twig.order_extension:
        class: AppBundle\Twig\OrderExtension
        arguments:    ['@service_container', '@biz']
        public: true
        tags:
            - { name: twig.extension }

    web.twig.course_extension:
        class: AppBundle\Twig\CourseExtension
        arguments:    ['@service_container', '@biz']
        public: true
        tags:
            - { name: twig.extension }

    web.twig.search_extension:
        class: AppBundle\Twig\SearchExtension
        arguments:    ['@service_container', '@biz']
        public: true
        tags:
            - { name: twig.extension }

    topxia.timemachine:
        class: AppBundle\Common\TimeMachine
        arguments:    ['Asia/Shanghai']
        public: true

    web.wrapper:
        class: AppBundle\Component\Wrapper\WrapperManage
        arguments: ['@service_container']
        public: true

    export_factory:
        class: AppBundle\Component\Export\Factory
        arguments: ['@service_container']
        public: true

    qrcode_whitelist_filter:
        class: AppBundle\Component\QrCode\QrCodeWhiteListFilter
        arguments: ['@service_container']
        public: true