<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_resource_kernel' shared service.

return $this->services['api_resource_kernel'] = new \ApiBundle\Api\ResourceKernel($this);
