<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'course_classroom_course_expiry_date_event_subscriber' shared service.

return $this->services['course_classroom_course_expiry_date_event_subscriber'] = new \Biz\Course\Event\ClassroomCourseExpiryDateEventSubscriber(${($_ = isset($this->services['biz']) ? $this->services['biz'] : $this->getBizService()) && false ?: '_'});
