<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oauth2.storage.client_credentials' shared service.

return $this->services['oauth2.storage.client_credentials'] = new \OAuth2\ServerBundle\Storage\ClientCredentials(${($_ = isset($this->services['doctrine.orm.entity_manager']) ? $this->services['doctrine.orm.entity_manager'] : $this->load('getDoctrine_Orm_EntityManagerService.php')) && false ?: '_'});
