<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oauth2.user_provider' shared service.

return $this->services['oauth2.user_provider'] = new \Biz\User\UserProvider(${($_ = isset($this->services['doctrine.orm.entity_manager']) ? $this->services['doctrine.orm.entity_manager'] : $this->load('getDoctrine_Orm_EntityManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['security.encoder_factory']) ? $this->services['security.encoder_factory'] : $this->load('getSecurity_EncoderFactoryService.php')) && false ?: '_'});
