<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'user.login_generate_notification_handler' shared service.

return $this->services['user.login_generate_notification_handler'] = new \AppBundle\Handler\GenerateNotificationHandler($this);
